# Generated by Django 5.2.1 on 2025-06-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='Логотип')),
                ('banner', models.ImageField(upload_to='banner', verbose_name='Баннер')),
                ('facebook', models.URLField(verbose_name='facebook')),
                ('twitter', models.URLField(verbose_name='twitter')),
                ('google', models.URLField(verbose_name='google')),
                ('linkedin', models.URLField(verbose_name='linkedin')),
            ],
        ),
    ]
