# Generated by Django 5.2.1 on 2025-06-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_galary_alter_setting_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Galary',
            new_name='Gallary',
        ),
    ]
